### ISSUE TITLE
Class 'TYPO3\CMS\Backend\View\Wizard\Element\BackendLayoutWizardElement' not found

### ISSUE THREAD

**Issue by FuntasticMedia** [CodersCare/gridelements#12]
While creating a new or editing an existing CE Backend Layout Element with the Developer Version 11.0.0-dev and Typo3 Version 11.5. you'll receive a 503 Error: Class 'TYPO3\CMS\Backend\View\Wizard\Element\BackendLayoutWizardElement' not found.

**Comment by Cybercraft-GmbH** [comment]
Thanks a lot for your contribution, but there already is an early access repository where we are creating a new version of Gridelements, that is already compatible to both - CMS 10 and 11 - and both - PHP 7.x and 8x - too.

The current master of this repository is not supposed to be working with CMS 11 yet.

if you want to get access to the private repository, you can sponsor our crowd funding campaign, which can be found here:
https://coders.care/for/crowdfunding/gridelements/support

Since this version will tackle the issue we will close the PR here.
