### ISSUE TITLE
Errror when dragging content element in TYPO3 11

### ISSUE THREAD

**Issue by anx-mwutte** [CodersCare/gridelements#18]
When trying to move an element via drag'n'drop within page module, the following errors are thrown:

_**1: Attempt to insert record on page '[root-level]' (0) where this table, tt_content, is not allowed**_

_**1: Attempt to move record 'XXX' (tt_content:123) without having permissions to insert.**_

TYPO3 11.5.21
Ext-Version: dev-master (2022-12-20)

**Comment by Bunnyfield** [comment]
Thanks a lot for your contribution, but there already is an early access repository where we are creating a new version of Gridelements, that is already compatible to both - CMS 10 and 11 - and both - PHP 7.x and 8x - too.

The current master of this repository is not supposed to be working with CMS 11 yet.

if you want to get immediate access to the private repository, you can sponsor our crowd funding campaign, which can be found here:
https://coders.care/for/crowdfunding/gridelements/support

Since this version will tackle the issue we will close the issue here.
