### ISSUE TITLE
TYPO3 v11 warning

### ISSUE THREAD

**Issue by dmitryd** [CodersCare/gridelements#21]
Running `typo3cms cache:flush`:

```
Warning: Undefined array key "shadowColumnsForNewPlaceholders" in /var/www/html/public/typo3conf/ext/gridelements/Configuration/TCA/Overrides/tt_content.php line 113
```

This option is obsolete: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.0/Breaking-92791-NewPlaceholderRecordsRemovedInWorkspaces.html

**Comment by Bunnyfield** [comment]
The current public version of Gridelements i s not supposed to run with CMS 11 yet. If you need Gridelements for CMS 11, you can get access to a private repository for sponsors by supporting our crowd funding campaign here:

https://coders.care/for/crowdfunding/gridelements/support

Of course this bug is fixed there and the version you get there will be running with CMS 10 or 11 and PHP version 7.4, 8.0 and 8.1
