### ISSUE TITLE
no rendering of gridelements in backend

### ISSUE THREAD

**Issue by dspenner** [CodersCare/gridelements#29]
Since upgrading gridelements to version 11, the elements of the grids are no longer rendered.

![grafik](https://user-images.githubusercontent.com/72801244/235913633-6ef909da-cd01-46f5-b739-98da46e4d511.png)

## Code Page.ts
```
lib.gridelements.defaultGridSetup {
  columns {
    default {
      renderObj = COA
      renderObj {
        20 =< tt_content
      }
    }
  }
  cObject =< lib.contentElement
  cObject.templateName = Generic
}

tt_content.gridelements_pi1.20.10.setup {
  5 < lib.gridelements.defaultGridSetup
  5 {
	  cObject = FLUIDTEMPLATE
	  cObject {
		file = EXT:my_template/Resources/Private/Gridelements/col-50-50.html
	  }
  }
}
```

## HTML Code:
```
<div class="FlexContainer">
    <div class="col1 col-50-50 Border">
			<!-- {data.tx_gridelements_view_column_89->f:format.raw()} -->
      <f:format.raw>{data.tx_gridelements_view_column_89}</f:format.raw>
		</div>

		<div class="col2 col-50-50 Border">
			<!-- {data.tx_gridelements_view_column_88->f:format.raw()}       -->
      <f:format.raw>{data.tx_gridelements_view_column_88}</f:format.raw>
		</div>
</div>
```

## Backend Layout Page TS
```
mod.web_layout.BackendLayouts {
  exampleKey {
    title = Example
    icon = EXT:example_extension/Resources/Public/Images/BackendLayouts/default.gif
    config {
      backend_layout {
        colCount = 2
        rowCount = 1
        rows {
          1 {
            columns {
              1 {
                name = 50%
                colPos = 89
              }
              2 {
                name = 50%
                colPos = 88
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by Bunnyfield** [comment]
The screen shot looks as if there are no child elements connected anymore - so you most likely did a Database-MIgration with Gridelements uninstalled, which breaks the colPos field definition and results in colPos 0 instead of -1.

If so, there is a new scheduler task with Gridelements 11, that can help you to get back the broken values.

**Comment by Bunnyfield** [comment]
You can check, if the DB values are the problem by looking at one of the child elements. If it has got a colPos value of 0, that's most likely due to the Database-Analyse step of the Install-Tool.

The task to fix this can be found in the scheduler - just go there and create a new task, then pick the necessary task from the list of Gridelements tasks. After saving it, you can run it by clicking on the play button.

**Comment by Bunnyfield** [comment]
OK - if those values are actually correct, the next option is a missing information about the container structure, that leads to the missing rendering of the preview,

`mod.web_layout.BackendLayouts`

seems to be wrong, so are you sure, this is the configuration for your container?

**Comment by Bunnyfield** [comment]
Thanks for the feedback.

Just for the record: While upgrading form TYPO3 CMS 10 to 11 there is no need to uninstall Gridelements, since you can already upgrade Gridelements before the actual core upgrade, because it is comptaible to both CMS 10 and 11.

If you still upgrade the core with uninstalled extensions, you have to make sure to not touch the colPos field of tt_content at all. So you have to manually uncheck the box in the Database Analyser before executing the update.

See: https://docs.typo3.org/p/gridelementsteam/gridelements/main/en-us/Chapters/Notes/Index.html
