### ISSUE TITLE
Plugin brakes list module on PgSQL

### ISSUE THREAD

**Issue by BoresXP** [CodersCare/gridelements#34]
DatabaseRecordList::getDBlistQuert adds where clause that brakes list module is running Typo3 on PgSQL:

>  Doctrine\DBAL\Exception\InvalidFieldNameException
> An exception occurred while executing 'SELECT COUNT(*) FROM "tt_content" WHERE (colPos != -1) AND (("sys_language_uid" <= 0) OR ("l18n_parent" = 0)) AND ("tt_content"."pid" = ?) AND (("tt_content"."deleted" = 0) AND (("tt_content"."t3ver_wsid" = 0) AND (("tt_content"."t3ver_oid" = 0) OR ("tt_content"."t3ver_state" = 4)))) LIMIT 1' with params [6]: SQLSTATE[42703]: Undefined column: 7 ERROR: column "colpos" does not exist LINE 1: SELECT COUNT(*) FROM "tt_content" WHERE (colPos != -1) AND (... ^ HINT: Perhaps you meant to reference the column "tt_content.colPos".

The issue here is in colPos field name added without double quotes. By default PgSQL converts all field names to lowercase. But PgSQL itself is case sensitive. And field is actually named colPos in tt_content table.
So, you have to add quotes to fix this issue:
`$additionalWhereClause .= ' AND "colPos" != -1 ';`
But this dirty fix can break Typo3 on other databases. Have to find better solution. I believe it should be done with QueryBuilder.

**Comment by Bunnyfield** [comment]
The problem in this case is caused by the core, because it does not make use of the QueryBuilder to generate the additional where clauses within the hook at all. Instead it expects a string, which is then converted to something more or less compatible to the query builder using a QueryHelper method.

```
if (!empty($addWhere)) {
    $queryBuilder->andWhere(QueryHelper::stripLogicalOperatorPrefix($addWhere));
}
```

Since the query builder is handled in a local variable, which is not made available to the hook, there is no chance to deal with this bug properly. So you should report this bug in the core tracker, since it is caused by the way the hook deals with anything provided by any extension making use of that hook and it is not restricted to Gridelements.

Escaping the given values properly should be done inside the condition.
