### ISSUE TITLE
In workspace deleted records still shown

### ISSUE THREAD

**Issue by 599media** [CodersCare/gridelements#39]
Using release 11.0.0, we ran into the following problem with workspaces and gridelements:

In the live environment a container with a regular content element exists.
After switching to a workspace and deleting the regular ce, it is still shown and ,further more, the new workspace version with t3ver_state = 2 is shown too. 
Trying to edit one of those records results in the error "Record with uid "xxx" from table "tt_content" is a workspace delete placeholder record which can not be edited."

By studying the EXT:backend/Classes/View/BackendLayout/ContentFetcher.php class we could fix this problem by adjusting the restrictions of the querybuilder and adding the getResults method to get rid of workspace deleted records in EXT:gridelements/Classes/Helper/Helper.php class

Our changes can be seen in the attached patch file.

[deleted_workspace_records.patch](https://github.com/CodersCare/gridelements/files/11786684/deleted_workspace_records.patch)

**Comment by Cybercraft-GmbH** [comment]
Since the helper class should be as generic as possible and will be used by both TYPO3 versions (10 and 11) which are supported by Gridelements 11, it would be less risky to skip superfluous elements in the foreach loop of the PreviewRenderer instead.

Willl be part of the next maintenance release, which is currently prepared in the early access repository.
