### ISSUE TITLE
Colspan has no effect PageModule when using Fluid rendering

### ISSUE THREAD

**Issue by YKWeyer** [CodersCare/gridelements#53]
When using `fluidBasedPageModule` on TYPO3 v11, the `colCount` / `colspan` keys has no effect on the rendering in the Page module. All columns will automatically be adjusted based on their content.

It seems to be caused by the lack of a `<colgroup>` tag inside the grids `<table>`

**Comment by Cybercraft-GmbH** [comment]
colspan has nothing to do with adjusted widths of table cells or their respective ration to each other. It just determines the way table cells overlap each other.

Since a fixed maximum width of a cell will break the rendering of nested Gridelements at a certain point, this behaviour most likely won't change in the near future. Even colgroup tags could only determine a minimum width, but would not help to fix that problem completely, since a maximum width again would break nested structures.

**Comment by YKWeyer** [comment]
> Since a fixed maximum width of a cell will break the rendering of nested Gridelements at a certain point, this behaviour most likely won't change in the near future

I am very sorry for the lack of clarity, but it is _not_ a feature request but a bug report.

This is something that used to work, and that probably still works when the fluid rendering is disabled, since it still is part of the [DrawItem::renderGridLayoutTable](https://github.com/CodersCare/gridelements/blob/e16b95c713665602b75a131805524ce76fc1c1ad/Classes/Hooks/DrawItem.php#L1115-L1119C32) logic.
