### ISSUE TITLE
missing array key 0

### ISSUE THREAD

**Issue by ToGetATockenOnly** [CodersCare/gridelements#66]
https://github.com/CodersCare/gridelements/blob/e16b95c713665602b75a131805524ce76fc1c1ad/Classes/Backend/TtContent.php#L223

comes up with PHPv8.1 and TYPO3v12

**Comment by Bunnyfield** [comment]
Since the current public Gridelements version is not compatible to CMS 12, I will close this issue here. Most likely it will be tackled by the version provided in the Early Access Repository you can get access to via sponsoring. The process is explained here:

https://coders.care/blog/article/together-we-grow

If not, feel free to reopen the issue as soon as the public release happened.
