### ISSUE TITLE
Error ::getPageInfo(): Return value must be of type array, null returned

### ISSUE THREAD

**Issue by matin73** [CodersCare/gridelements#73]
I get error in combination with extension frontend_editing in TYPO3 11 (PHPH 7.4 and PHP 8x):
TYPO3\CMS\Backend\Controller\ContentElement\NewContentElementController::getPageInfo(): Return value must be of type array, null returned
in /usr/local/www/bbbb/xxx/typo3/sysext/backend/Classes/Controller/ContentElement/NewContentElementController.php line 523

at TYPO3\CMS\Backend\Controller\ContentElement\NewContentElementController->getPageInfo()
in /usr/local/www/apache24/xxx/xxx/typo3conf/ext/gridelements/Classes/Hooks/WizardItems.php line 71
    {
        if (!$this->getBackendUser()->checkAuthMode('tt_content', 'CType', 'gridelements_pi1', $GLOBALS['TYPO3_CONF_VARS']['BE']['explicitADmode'])) {
            return;
        }
        $pageInfo = $parentObject->getPageInfo();
        $pageId = (int)$pageInfo['uid'];
        $this->init($pageId);

        $container = (int)GeneralUtility::_GP('tx_gridelements_container');

**Comment by Bunnyfield** [comment]
Hi @matin73 thanks for the report, but it seems that we can't do anything about it from the Gridelements side:

Neither the getPageInfo() method, nor the NewContentElementController are provide by Gridelements.
So there is no way to change the behaviour of those methods.

That's why I will close the issue here and recommend checking either the frontend_editing extension or the core for possible bugs.

AFAICS the core provides either the page access information or an empty array, so I guess the culprit should be frontend_editing in this case.

Feel free to reopne the issue, if you found other evidence.
