### ISSUE TITLE
Forms within gridelements does not render

### ISSUE THREAD

**Issue by pascaloberhaensli** [CodersCare/gridelements#76]
gridelements version: 12.0.0
typo3: 12.4.23

As soon as a form output (Typo3 Standard Forms) is within a gridelements element the {formConfiguration} is not present. We could follow the issue until Render.html (sysext\form\Resources\Private\Frontend\Templates\Render.html). The if condition is not true, so no form is rendered. 

![image](https://github.com/user-attachments/assets/63865400-65dc-4ec8-a672-02a4aac35266)

**Comment by Bunnyfield** [comment]
@pascaloberhaensli Since the core form is working with pi_flexform for configurations, you might want to check your Gridelements configuration regarding

```
resolveFlexFormData
resolveChildFlexFormData
```
See https://docs.typo3.org/p/gridelementsteam/gridelements/main/en-us/Chapters/DataProcessing/Reference/Index.html#dataprocessing-123-default-options-resolvechildflexformdata

both are active by default, which resolves Flexforms directly into the cObj.data array to access them form within your Fluid template. If you want the original plugin to do the job, leaving the Flexform value as is, you should deactivate at least

`resolveChildFlexFormData = 0`
