### ISSUE TITLE
Duplicate content with translated items inside an "All" languages gridelement

### ISSUE THREAD

**Issue by github1maxserv** [CodersCare/gridelements#8]
A two-column gridelement was set to Language "All". Content elements inside the container were translated.
In frontend the translated page shows the translated content elements twice.

Apparently in the translated page both elements are fetched and with the language overlay the element in the default language gets the content from the translation too.

![AllLanguagesGrid](https://user-images.githubusercontent.com/87801194/193028562-019e163c-88c6-4f09-b6c8-2cf0d8980fbb.jpg)

**Comment by Cybercraft-GmbH** [comment]
This topic has been discussed recently within the other issue tracker on Gitlab and additionally put on stack overflow.
Closing the issue here due to the reasons described in the comments there.

https://stackoverflow.com/questions/72604089/typo3-v10-fix-translated-contentelements-within-gridelements-with-language-all
